// Type: Reducer
export const FETCH_EVENTS_REQUEST = "FETCH_EVENTS_REQUEST";
export const FETCH_EVENTS_FAILURE = "FETCH_EVENTS_FAILURE";
export const FETCH_EVENTS_SUCCESS = "FETCH_EVENTS_SUCCESS";
export const EDIT_MODAL_STATE = "EDIT_MODAL_STATE";
export const CREATE_MODAL_STATE = "CREATE_MODAL_STATE";
export const TOKEN_STATE = "TOKEN_STATE";
export const USER_STATE = "USER_STATE";